### ISSUE TITLE
https://plausible.io/js/script.js is not loaded on Firefox

### ISSUE THREAD

**Issue by Jean-BaptisteC** [WilliamTraoreee/blog#16]
Website on Firefox shows on console warning:
`Échec du chargement pour l’élément <script> dont la source est « https://plausible.io/js/script.js ».`
No problem on Edge

**Comment by WilliamTraoreee** [comment]
I don't have this issue on Firefox. It's not a big bug because it's just for stat purpose.

**Comment by Jean-BaptisteC** [comment]
I think, it's caused by my ads block or Firefox settings to reduce tracking
