### ISSUE TITLE
Wrong width in search bar

### ISSUE THREAD

**Issue by Jean-BaptisteC** [WilliamTraoreee/blog#18]
Start search - > The width of search bar has been reduced because the back button is present on search page

**Comment by WilliamTraoreee** [comment]
Do you have a screen for that ? I don't see any problème on my side

**Comment by Jean-BaptisteC** [comment]
Main page
<img src="https://github.com/WilliamTraoreee/blog/assets/87148630/129d971d-d804-48e9-b146-b21c0372f246" height=50 /> 
Search page
<img src="https://github.com/WilliamTraoreee/blog/assets/87148630/3028ea3f-b8b7-4a72-a459-24654e142bef" height=50 />

**Comment by WilliamTraoreee** [comment]
I'm ok with that for now, I think I'll redesign all this part later because it don't need to be on the top of each page
