### ISSUE TITLE
Reduce width search bar on mobile to leave more space for back button

### ISSUE THREAD

**Issue by Jean-BaptisteC** [WilliamTraoreee/blog#19]
On mobile, the search bar takes all width of page.
I suggest reducing size of search bar to leave more space between the back button and the search bar in search page

| Main | Search Page |
| - | - |
| <img src="https://github.com/WilliamTraoreee/blog/assets/87148630/8a6d5079-6380-4fb8-82dd-e14133eb09af" height=400 /> | <img src="https://github.com/WilliamTraoreee/blog/assets/87148630/e704f2fb-40ce-4d88-915d-6fbe3468cdce" height=400 /> |

**Comment by WilliamTraoreee** [comment]
I think here the major issue is the gap between the back button and the input. I fix that on the last PR so it will be live now :)
