### ISSUE TITLE
Body overflow issue on mobile (iPhone X - X.com webview)

### ISSUE THREAD

**Issue by VictorPolouchine** [WilliamTraoreee/blog#8]
Hello Will, just a small issue to alert on the current mobile behavior ! Feel free to delete this if it's intrusive or not relevant 🙏🏻
Loved your content on StrealiApp, keep it up 💪

![image](https://github.com/WilliamTraoreee/blog/assets/65499073/f796b1d0-f9ac-45e4-a43e-01ae4c779c01)

**Comment by WilliamTraoreee** [comment]
Hi @VictorPolouchine 

Thanks for your feedback. It' sa valid issue. I'll fix that today
